# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Projects\BashNipiNeft\client\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 380)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 380))
        MainWindow.setMaximumSize(QtCore.QSize(800, 380))
        MainWindow.setBaseSize(QtCore.QSize(800, 380))
        font = QtGui.QFont()
        font.setFamily("Roboto,sans-serif")
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setStatusTip("")
        MainWindow.setStyleSheet("QMainWindow {\n"
"    color: #292929;\n"
"    font-family: \'Roboto\', sans-serif;\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #292929;\n"
"    font-family: \'Roboto\', sans-serif;\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border-radius: 10px;\n"
"    border: 2px solid #e9e9e9;\n"
"    color: #292929;\n"
"    font-family: \'Roboto\', sans-serif;\n"
"    font-size: 11pt;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0086d7;\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-family: \'Roboto\', sans-serif;\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #fff;\n"
"    color: #292929;\n"
"    border: 1px solid #7db1d0;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    color: #292929;\n"
"    border: 2px solid #e9e9e9;\n"
"    border-radius: 10px;\n"
"    font-family: \'Roboto\', sans-serif;\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    color: #292929;\n"
"    font-family: \'Roboto\', sans-serif;\n"
"    font-size: 11pt;\n"
"}")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 130, 780, 181))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setLineWidth(2)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 90, 520, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.input_year = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.input_year.setMinimumSize(QtCore.QSize(60, 30))
        self.input_year.setMaximumSize(QtCore.QSize(60, 30))
        self.input_year.setMaxLength(4)
        self.input_year.setAlignment(QtCore.Qt.AlignCenter)
        self.input_year.setObjectName("input_year")
        self.horizontalLayout.addWidget(self.input_year)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.input_discount_rate = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.input_discount_rate.setMinimumSize(QtCore.QSize(60, 30))
        self.input_discount_rate.setMaximumSize(QtCore.QSize(60, 30))
        self.input_discount_rate.setMaxLength(6)
        self.input_discount_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.input_discount_rate.setObjectName("input_discount_rate")
        self.horizontalLayout.addWidget(self.input_discount_rate)
        self.btn_count = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_count.setMinimumSize(QtCore.QSize(85, 30))
        self.btn_count.setMaximumSize(QtCore.QSize(85, 30))
        self.btn_count.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_count.setObjectName("btn_count")
        self.horizontalLayout.addWidget(self.btn_count)
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(700, 320, 85, 30))
        self.btn_close.setMinimumSize(QtCore.QSize(85, 30))
        self.btn_close.setMaximumSize(QtCore.QSize(85, 30))
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 31, 277, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.input_host = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.input_host.setMinimumSize(QtCore.QSize(120, 30))
        self.input_host.setMaximumSize(QtCore.QSize(120, 30))
        self.input_host.setMaxLength(15)
        self.input_host.setAlignment(QtCore.Qt.AlignCenter)
        self.input_host.setObjectName("input_host")
        self.horizontalLayout_2.addWidget(self.input_host)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.input_port = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.input_port.setMinimumSize(QtCore.QSize(60, 30))
        self.input_port.setMaximumSize(QtCore.QSize(60, 30))
        self.input_port.setMaxLength(6)
        self.input_port.setAlignment(QtCore.Qt.AlignCenter)
        self.input_port.setObjectName("input_port")
        self.horizontalLayout_2.addWidget(self.input_port)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 151, 16))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 80, 780, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(600, 320, 85, 30))
        self.btn_clear.setMinimumSize(QtCore.QSize(85, 30))
        self.btn_clear.setMaximumSize(QtCore.QSize(85, 30))
        self.btn_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_clear.setStyleSheet("#btn_clear {\n"
"    background-color: #fff;\n"
"    color: #292929;\n"
"    border: 1px solid #7db1d0;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#btn_clear:hover {\n"
"    background-color: #0086d7;\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"}")
        self.btn_clear.setObjectName("btn_clear")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Год расчета:"))
        self.label_3.setText(_translate("MainWindow", "Cтавка дисконтирования:"))
        self.btn_count.setText(_translate("MainWindow", "Расчет"))
        self.btn_close.setText(_translate("MainWindow", "Закрыть"))
        self.label_4.setText(_translate("MainWindow", "host:"))
        self.label_5.setText(_translate("MainWindow", "port:"))
        self.label.setText(_translate("MainWindow", "Настройки сервера:"))
        self.btn_clear.setText(_translate("MainWindow", "Очистить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
